### ISSUE TITLE
Customise ident symbol

### ISSUE THREAD

**Issue by rprieto** [entwicklerstube/listr-multiline-renderer#1]
Hi, are you interested in a PR to customise the indentation symbol, by default `→`?

If we use the `options` parameter in `const renderHelper = (tasks, options, level) => {`, where is that specified from a consumer point of view?

**Comment by michaelzoidl** [comment]
Hey @rprieto sorry for the delay... sounds good, make a PR :) so we can release a new version with this feature.. thanks

**Comment by rprieto** [comment]
hi @michaelzoidl, sorry it wasn't clear: #3 only adds unit tests for the current behaviour as I didn't want to break anything. I still need to do a PR for customising the indent symbol.
